use std::os::raw::c_int;
use crate::sys::*;

pub fn unix_err_to_string(value: c_int) -> &'static str {
	match value {
		v if v == EPERM => "Operation not permitted",
		v if v == ENOENT => "No such file or directory",
		v if v == ESRCH => "No such process",
		v if v == EINTR => "Interrupted system call",
		v if v == EIO => "I/O error",
		v if v == ENXIO => "No such device or address",
		v if v == E2BIG => "Arg list too long",
		v if v == ENOEXEC => "Exec format error",
		v if v == EBADF => "Bad file number",
		v if v == ECHILD => "No child processes",
		v if v == EAGAIN => "Try again",
		v if v == ENOMEM => "Out of memory",
		v if v == EACCES => "Permission denied",
		v if v == EFAULT => "Bad address",
		v if v == ENOTBLK => "Block device required",
		v if v == EBUSY => "Device or resource busy",
		v if v == EEXIST => "File exists",
		v if v == EXDEV => "Cross-device link",
		v if v == ENODEV => "No such device",
		v if v == ENOTDIR => "Not a directory",
		v if v == EISDIR => "Is a directory",
		v if v == EINVAL => "Invalid argument",
		v if v == ENFILE => "File table overflow",
		v if v == EMFILE => "Too many open files",
		v if v == ENOTTY => "Not a typewriter",
		v if v == ETXTBSY => "Text file busy",
		v if v == EFBIG => "File too large",
		v if v == ENOSPC => "No space left on device",
		v if v == ESPIPE => "Illegal seek",
		v if v == EROFS => "Read-only file system",
		v if v == EMLINK => "Too many links",
		v if v == EPIPE => "Broken pipe",
		v if v == EDOM => "Math argument out of domain of func",
		v if v == ERANGE => "Math result not representable",
		v if v == EDEADLK => "Resource deadlock would occur",
		v if v == ENAMETOOLONG => "File name too long",
		v if v == ENOLCK => "No record locks available",
		v if v == ENOSYS => "Function not implemented",
		v if v == ENOTEMPTY => "Directory not empty",
		v if v == ELOOP => "Too many symbolic links encountered",
		v if v == EWOULDBLOCK => "Operation would block",
		v if v == ENOMSG => "No message of desired type",
		v if v == EIDRM => "Identifier removed",
		v if v == ECHRNG => "Channel number out of range",
		v if v == EL2NSYNC => "Level 2 not synchronized",
		v if v == EL3HLT => "Level 3 halted",
		v if v == EL3RST => "Level 3 reset",
		v if v == ELNRNG => "Link number out of range",
		v if v == EUNATCH => "Protocol driver not attached",
		v if v == ENOCSI => "No CSI structure available",
		v if v == EL2HLT => "Level 2 halted",
		v if v == EBADE => "Invalid exchange",
		v if v == EBADR => "Invalid request descriptor",
		v if v == EXFULL => "Exchange full",
		v if v == ENOANO => "No anode",
		v if v == EBADRQC => "Invalid request code",
		v if v == EBADSLT => "Invalid slot",
		v if v == EDEADLOCK => "Deadlock",
		v if v == EBFONT => "Bad font file format",
		v if v == ENOSTR => "Device not a stream",
		v if v == ENODATA => "No data available",
		v if v == ETIME => "Timer expired",
		v if v == ENOSR => "Out of streams resources",
		v if v == ENONET => "Machine is not on the network",
		v if v == ENOPKG => "Package not installed",
		v if v == EREMOTE => "Object is remote",
		v if v == ENOLINK => "Link has been severed",
		v if v == EADV => "Advertise error",
		v if v == ESRMNT => "Srmount error",
		v if v == ECOMM => "Communication error on send",
		v if v == EPROTO => "Protocol error",
		v if v == EMULTIHOP => "Multihop attempted",
		v if v == EDOTDOT => "RFS specific error",
		v if v == EBADMSG => "Not a data message",
		v if v == EOVERFLOW => "Value too large for defined data type",
		v if v == ENOTUNIQ => "Name not unique on network",
		v if v == EBADFD => "File descriptor in bad state",
		v if v == EREMCHG => "Remote address changed",
		v if v == ELIBACC => "Can not access a needed shared library",
		v if v == ELIBBAD => "Accessing a corrupted shared library",
		v if v == ELIBSCN => ".lib section in a.out corrupted",
		v if v == ELIBMAX => "Attempting to link in too many shared libraries",
		v if v == ELIBEXEC => "Cannot exec a shared library directly",
		v if v == EILSEQ => "Illegal byte sequence",
		v if v == ERESTART => "Interrupted system call should be restarted",
		v if v == ESTRPIPE => "Streams pipe error",
		v if v == EUSERS => "Too many users",
		v if v == ENOTSOCK => "Socket operation on non-socket",
		v if v == EDESTADDRREQ => "Destination address required",
		v if v == EMSGSIZE => "Message too long",
		v if v == EPROTOTYPE => "Protocol wrong type for socket",
		v if v == ENOPROTOOPT => "Protocol not available",
		v if v == EPROTONOSUPPORT => "Protocol not supported",
		v if v == ESOCKTNOSUPPORT => "Socket type not supported",
		v if v == EOPNOTSUPP => "Operation not supported on transport endpoint",
		v if v == EPFNOSUPPORT => "Protocol family not supported",
		v if v == EAFNOSUPPORT => "Address family not supported by protocol",
		v if v == EADDRINUSE => "Address already in use",
		v if v == EADDRNOTAVAIL => "Cannot assign requested address",
		v if v == ENETDOWN => "Network is down",
		v if v == ENETUNREACH => "Network is unreachable",
		v if v == ENETRESET => "Network dropped connection because of reset",
		v if v == ECONNABORTED => "Software caused connection abort",
		v if v == ECONNRESET => "Connection reset by peer",
		v if v == ENOBUFS => "No buffer space available",
		v if v == EISCONN => "Transport endpoint is already connected",
		v if v == ENOTCONN => "Transport endpoint is not connected",
		v if v == ESHUTDOWN => "Cannot send after transport endpoint shutdown",
		v if v == ETOOMANYREFS => "Too many references: cannot splice",
		v if v == ETIMEDOUT => "Connection timed out",
		v if v == ECONNREFUSED => "Connection refused",
		v if v == EHOSTDOWN => "Host is down",
		v if v == EHOSTUNREACH => "No route to host",
		v if v == EALREADY => "Operation already in progress",
		v if v == EINPROGRESS => "Operation now in progress",
		v if v == ESTALE => "Stale NFS file handle",
		v if v == EUCLEAN => "Structure needs cleaning",
		v if v == ENOTNAM => "Not a XENIX named type file",
		v if v == ENAVAIL => "No XENIX semaphores available",
		v if v == EISNAM => "Is a named type file",
		v if v == EREMOTEIO => "Remote I/O error",
		v if v == EDQUOT => "Quota exceeded",
		v if v == ENOMEDIUM => "No medium found",
		v if v == EMEDIUMTYPE => "Wrong medium type",
		_ => "",
	}
}

